### ISSUE TITLE
Creación de scripts de base de datos

### ISSUE THREAD

**Issue by DenisAGS** [obedhipolito/Biblioteca_web#5]
**Descripcion**
Debemos desarrollar y documentar los scripts de la base de datos necesarios para el proyecto. Estos scripts son muy importantes para el funcionamiento de la aplicación y deben estar debidamente diseñados y gestionados.

**Task**
- [ ] Diseñar el esquema de la base de datos, incluyendo tablas, relaciones y campos.
- [ ] Crear scripts de creación de tablas.
- [ ] Generar scripts de población inicial de datos.
- [ ] Documentar los scripts de la base de datos.
